codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0.5%
    patch:
      default:
        target: 80%
        threshold: 0.5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: true